### ISSUE TITLE
build a web application to submit images and view results

### ISSUE THREAD

**Issue by Foxman13** [CatalystCode/faceanalysis#5]
Need to build a front-end web application that will allow a user to submit a photo or batch of photos to compare against what's stored in the face database. We can base this off of the imaginem web interface or we can start from scratch.

**Comment by TechPreacher** [comment]
Batch image uploader added to the "frontend" branch. https://github.com/CatalystCode/faceanalysis/tree/frontend/frontend/image-uploader
